copied build from production

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -124,43 +124,43 @@ jobs:
   vue:
     executor: docker/docker
     steps:
-      - setup_remote_docker:
-          docker_layer_caching: true
+      - setup_remote_docker
       - checkout
+      - run:
+          name: "Check Required Environment Variables"
+          command: |
+            required_vars=(
+              API_BASEURL API_HOSTNAME APP_HOSTNAME ROLLBAR_ACCESS_TOKEN 
+              LANDING_HOSTNAME GOOGLE_ANALYTICS_ID CRISP_WEBSITE_ID ENTERPRISE 
+              ENVIRONMENT VUE_APP_API_HOSTNAME GOOGLE_MAPS_APIKEY
+              VUE_APP_ROLLBAR_ACCESS_TOKEN VUE_APP_LANDING_HOSTNAME 
+              WEB_HOSTNAME
+            )
+
+            for var in "${required_vars[@]}"; do
+              if [ -z "${!var}" ]; then
+                echo "Environment variable $var is missing or empty."
+                exit 1
+              fi
+            done
+
+            echo "All required environment variables are present."
+      - run:
+          name: Fetch all dependencies (esp. console)
+          command: |
+            git submodule foreach --recursive 'git submodule sync' && git submodule update --init --recursive
       - docker/check:
           registry: registry.thinx.cloud:5000
       - docker/build:
           registry: registry.thinx.cloud:5000
-          docker-context: vue-dev
-          image: thinxcloud/console-build-env
-          dockerfile: vue-dev/Dockerfile
+          docker-context: services/console/vue
+          image: thinx/console
+          dockerfile: services/console/vue/Dockerfile
+          extra_build_args: --build-arg ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN} --build-arg LANDING_HOSTNAME=${LANDING_HOSTNAME} --build-arg API_HOSTNAME=${API_HOSTNAME} --build-arg API_BASEURL=${API_BASEURL} --build-arg WEB_HOSTNAME=${WEB_HOSTNAME} --build-arg GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID} --build-arg CRISP_WEBSITE_ID=${CRISP_WEBSITE_ID} --build-arg ENTERPRISE=${ENTERPRISE} --build-arg ENVIRONMENT=${ENVIRONMENT} --build-arg COMMIT_ID=$CIRCLE_SHA1 --build-arg VERSION_CODE=$(echo $CIRCLE_SHA1 | cut -c -7) --build-arg VUE_APP_CRISP_WEBSITE_ID=${CRISP_WEBSITE_ID} --build-arg VUE_APP_API_HOSTNAME=${VUE_APP_API_HOSTNAME} --build-arg VUE_APP_ROLLBAR_ACCESS_TOKEN=${VUE_APP_ROLLBAR_ACCESS_TOKEN} --build-arg VUE_APP_LANDING_HOSTNAME=${VUE_APP_LANDING_HOSTNAME} --build-arg VUE_APP_GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID} --build-arg VUE_APP_GOOGLE_MAPS_APIKEY=${GOOGLE_MAPS_APIKEY} --build-arg VUE_APP_CONSOLE_HOSTNAME=${WEB_HOSTNAME}
           tag: 'vue'
-      - docker/build:
-          registry: registry.thinx.cloud:5000
-          docker-context: vue
-          image: thinx/console
-          dockerfile: vue/Dockerfile
-          extra_build_args: |
-            --build-arg ROLLBAR_ACCESS_TOKEN=${ROLLBAR_ACCESS_TOKEN} \
-            --build-arg LANDING_HOSTNAME=${LANDING_HOSTNAME} \
-            --build-arg API_HOSTNAME=${API_HOSTNAME} \
-            --build-arg API_BASEURL=${API_BASEURL} \
-            --build-arg WEB_HOSTNAME=${WEB_HOSTNAME} \
-            --build-arg GOOGLE_ANALYTICS_ID=${GOOGLE_ANALYTICS_ID} \
-            --build-arg CRISP_WEBSITE_ID=${CRISP_WEBSITE_ID} \
-            --build-arg ENTERPRISE=${ENTERPRISE} \
-            --build-arg ENVIRONMENT=${ENVIRONMENT} \
-            --build-arg COMMIT_ID=$CIRCLE_SHA1 \
-            --progress=plain \
-          tag: 'latest'
       - docker/push:
           digest-path: /tmp/digest.txt
           image: thinx/console
-          registry: registry.thinx.cloud:5000
-          tag: 'latest'
-      - docker/push:
-          digest-path: /tmp/digest.txt
-          image: thinxcloud/console-build-env
           registry: registry.thinx.cloud:5000
           tag: 'vue'
 
